# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        cache: gradle
    - name: actions-setup-mysql
  # You may pin to the exact commit or the version.
  # uses: shogo82148/actions-setup-mysql@f009c43355912736b6dc8b0dc5aee33051d2f01b
      uses: shogo82148/actions-setup-mysql@v1.3.1
      with:
      # The version of MySQL and MariaDB
        mysql-version: 8.0.26 # optional, default is 
      # The distribution. valid values are mysql or mariadb.
        distribution: mysql # optional, default is mysql
      # Start MySQL server if it is true.
        auto-start: true # optional, default is true
    # my.cnf settings for mysqld
        my-cnf: my.cnf 
    # password for the root user
        root-password: password 
    # name of a new user
        user: root 
    # password for the new user
        password: password 
    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
